import datetime as dt
import json
from typing import Literal

import polars as pl

from vhf_pipeline import paths
from vhf_pipeline.pipeline.get_foundry_data import save_foundry_input

GLOBAL_L0_NAME = "global_L0_national_clean_daily.csv"
ISO3C_VALUES = Literal["COD", "UGA", "FRA"]


def _process_1cdp_confirmation_data(
    df: pl.DataFrame, max_data_date: dt.date, iso3c: list[ISO3C_VALUES]
) -> pl.DataFrame:
    """Process the 1CDP confirmation data to get daily confirmed cases.

    The source file is global, so it also carries cases exported to other
    countries. Those are not generated by the transmission process being
    calibrated, and summing them into the target would attribute them to it.
    """
    processed_data = (
        df.filter(pl.col("iso3c").is_in(iso3c))
        .select("date", "cases_confirmed_incident")
        .group_by("date")
        .agg(pl.sum("cases_confirmed_incident").alias("count"))
        .with_columns(pl.col("date").cast(pl.Date))
        .filter(pl.col("date") <= max_data_date)
        .with_columns(pl.lit("Confirmed").alias("case_status"))
        .sort("date")
    )
    return processed_data


def load_1cdp_confirmation(
    filename: str,
    iso3c: list[ISO3C_VALUES],
    max_data_date: dt.date | None = None,
    cache: bool = True,
) -> bool:
    if max_data_date is None:
        max_data_date = dt.date.today()

    cache_dir = (
        paths.data_input_dir() / ".cache" / f"max_date_{max_data_date.isoformat()}"
    )
    if cache and cache_dir.exists():
        print(f"Using cached data from {cache_dir}")
        processed_data = pl.read_csv(cache_dir / filename)
        processed_data.write_csv(paths.data_input_dir() / filename)
        new_data_used = False

    else:
        # Must precede the read: this call is what writes the CSV.
        save_foundry_input(
            filename=GLOBAL_L0_NAME,
            rid_override="global_L0_national_clean_daily",
            verbose=True,
        )
        raw_data = pl.read_csv(paths.data_input_dir() / GLOBAL_L0_NAME)

        # Process the raw data to get daily confirmed cases
        processed_data = _process_1cdp_confirmation_data(
            df=raw_data, max_data_date=max_data_date, iso3c=iso3c
        )
        processed_data.write_csv(paths.data_input_dir() / filename)

        if cache:
            max_date_obs = processed_data.select(pl.max("date")).item()
            if max_date_obs < max_data_date:
                cache_dir = (
                    paths.data_input_dir()
                    / ".cache"
                    / f"max_date_{max_date_obs.isoformat()}"
                )
            cache_dir.mkdir(parents=True, exist_ok=True)
            processed_data.write_csv(cache_dir / filename)
            raw_data.write_csv(cache_dir / GLOBAL_L0_NAME)

            meta_data = {
                "max_data_date": max_data_date.isoformat(),
                "max_date_observed": max_date_obs.isoformat(),
                "date_cached": dt.date.today().isoformat(),
            }
            with open(cache_dir / "metadata.json", "w") as f:
                json.dump(meta_data, f)
        new_data_used = True
    return new_data_used
